# Generated by Django 6.0.2 on 2026-07-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('medical_records', '0005_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='medical_records.medicalrecord'),
        ),
    ]
