# Generated by Django 5.1.7 on 2026-04-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_hospital_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorhospitalmembership',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
